name: CI

on:
  push:
    branches: [ main, v*.* ]
  pull_request:
    branches: [ main, v*.* ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # deep checkout for NerdBank.GitVersioning

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Pack
        run: dotnet pack --no-build -c Release -o pack

      # uncomment to push to nuget.org. don't forget to add the NUGET_API_KEY secret.
      #- name: Push
        #run: dotnet nuget push pack/*.nupkg -k ${{ secrets.NUGET_API_KEY }}
