name: CI

on:
  push:
    branches: [ main, v*.* ]
  pull_request:
    branches: [ main, v*.* ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore dependencies
        run: |
          dotnet restore --locked-mode
          dotnet tool restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Snapshot testing
        run: dotnet r test 

      - name: Pack
        run: dotnet pack --no-build -c Release -o pack

      - name: Push
        run: dotnet nuget push pack/*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
